#!/usr/bin/env bash
# A bash script that transfers a file from client to server
path=$1
ip=$2
uname=$3
private_key=$4
if [[ $# -gt 2 ]]
	then
		scp "$path" "$ip" "$uname" "$private_key"
	else
		echo "Usage: 0-transer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
