#!/usr/bin/env bash
# A bash script that transfers a file from client to server
if [[ $# -gt 2 ]]
	then
		scp -o  StrictHostKeyChecking=no -i "$4" "$1" "$2@$3" :
	else
		echo "Usage: 0-transer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
