#!/usr/bin/env bash
# A bash script that configures a new Ubuntu machine to install
# nginx on a web-01 server
apt-get -y update
apt-get -y install nginx
echo  'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
