#!/usr/bin/env bash
# A bash script that configures a new Ubuntu machine to install
# nginx on a web-01 server
apt-get -y update
apt-get -y install nginx
echo  'Holberton School for the win!' | sudo tee /var/www/html/index.nginx-debian.html
var="rewrite^/redirectme https://www.youtube.com/watch?v=QH2-TGUIwu4 permanent;"
sed -i "37i\$var/etc/nginx/sites-enable/default"
service nginx start
