#!/usr/bin/env bash
# Configures web-02 to be indentical to web-01 with a custom Nginx
# response header
# shellcheck disable=SC2154
apt-get -y update
apt-get -y install nginx
'35.231.12.153'@'localhost' {
	add_header X-Served-By: 1134-web-01
}
'54.234.188.78'@'localhost' {
	add_header X-Served-By: 1134-web-02
}
service nginx start
