#!/usr/bin/env bash
# This is a script displaying "To infinity and beyond" indefinitely, and then
# I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
i=0
while [ $i -lt 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done
