#!/usr/bin/env bash
# This script is displaying the story of the file /etc/passwd
i="/etc/passwd"
while IFS=: read -r username password userid groupid userinfo homedir cmdshell
do
    echo "The user $username is a part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < $i
