#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 mins
j=0
while [ $j -lt 13 ]
do
    echo "Hour: $j"
    i=1
    while [ $i -lt 60 ]
    do
        echo "$i"
        i=$(( i + 1 ))
	done
    j=$(( j + 1))
done
